name: my_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # HTTP requests
  http: ^1.4.0

  # Geolocation (for latitude & longitude)
  geolocator: ^10.1.0

  # Location tracking (check GPS, request enable, get current position)
  location: ^5.0.0

  # File picker
  file_picker: ^10.2.0


  # Open URLs (like launching Google Maps etc)
  url_launcher: ^6.2.1

  # Web view
  webview_flutter: ^4.13.0

  # Logging
  logging: ^1.2.0

  # Toast messages
  fluttertoast: ^8.2.5

  # State management
  provider: ^6.1.2

  # Environment variables
  flutter_dotenv: ^5.1.0

  # 📍 Map support
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/zawa_logo.png
    - assets/Unguja.png
    - assets/Pemba.png
